# -*- coding: utf-8 -*-
"""
/***************************************************************************
 madarak
                                 A QGIS plugin
                                 
 A plugin segítségével egy spatialite adatbázisba lehet feltölteni adatokat.
 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-13
        copyright            : (C) 2022 by András Lászlók
        email                : laszlokand@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load madarak class from file madarak.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .madarak import madarak
    return madarak(iface)
