# -*- coding: utf-8 -*-
"""
/***************************************************************************
 madarak
                                 A QGIS plugin
                                 
 A plugin segítségével egy spatialite adatbázisba lehet feltölteni adatokat.
 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-12-13
        git sha              : $Format:%H$
        copyright            : (C) 2022 by András Lászlók
        email                : laszlokand@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .madarak_widget import madarakWidget
import os.path, spatialite, sqlite3


class madarak:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'madarak_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&madarak')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('madarak', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/madarak/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&madarak'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the widget with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.widget = madarakWidget()

        # show the widget
        self.widget.show()
        self.widget.pushButton.pressed.connect(self.upload)


    def upload(self):
        """Upload data to database"""

        try:

            sqliteConnection = spatialite.connect(os.path.join(os.path.dirname(__file__), "madarak2.sqlite"))
            cursor = sqliteConnection.cursor()

            sqlite_insert_query = ("INSERT INTO madarak2 \
                              (faj, egyedszam, kozseg, kozseg_id, eov_e, eov_n) \
                              VALUES (?,?,?,?,?,?);")

            v_faj=self.widget.textEdit.toPlainText()
            v_egyedszam=self.widget.spinBox.value()
            v_kozseg=self.widget.textEdit_2.toPlainText()
            v_kozseg_id=self.widget.spinBox_2.value()
            v_eov_e=self.widget.doubleSpinBox.value()
            v_eov_n=self.widget.doubleSpinBox_2.value()

            data_tuple = (v_faj, v_egyedszam, v_kozseg, v_kozseg_id, v_eov_e, v_eov_n)

            cursor.execute(sqlite_insert_query, data_tuple)
            sqliteConnection.commit()
            
            cursor.execute('UPDATE madarak2 SET Geom=MakePoint(eov_e, eov_n, 23700) WHERE id = (SELECT MAX(id) FROM madarak2);')
            sqliteConnection.commit()

            self.widget.label_8.setText(f'Sikeres feltöltés: {v_faj}')

            cursor.close()

        except sqlite3.Error as error:
            self.widget.label_8.setText(f'Sikertelen feltöltés: {error}')

        finally:
            if sqliteConnection:
                sqliteConnection.close()
